services:
  redis:
    image: redis:7.4.0-alpine3.20
    container_name: showcase--redis
    ports:
      - host_ip: 0.0.0.0
        published: 6380 # host
        target: 6379 # container
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: showcase--redis--data
        target: /data
    # Custom command to enable persistance
    command: ['redis-server', '--appendonly', 'yes']
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping || exit 1']
      interval: 5s

  # Browser URL:
  # http://localhost:8880
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:1.19.3
    container_name: showcase--phpredisadmin
    ports:
      - host_ip: 0.0.0.0
        published: 8880 # host
        target: 80 # container
        protocol: tcp
        mode: host
    environment:
      REDIS_1_HOST: showcase--redis
      REDIS_1_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy

volumes:
  showcase--postgres--data:
    name: showcase--postgres--data
  showcase--redis--data:
    name: showcase--redis--data

networks:
  default:
    name: showcase--network--default
